spring:
  datasource:
    url: jdbc:mysql://localhost:3306/game?characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hzy123
server:
  port: 8050

  #自定义常量?#TODO 注入不进去待解决
playerdata:
  HP: 100
  money: 1000
  efficiency: 100
  #每次升级+100
  upEfficiency: 100


